# Generated by Django 4.2.4 on 2023-08-07 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FarmPics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Farm_pics', models.ImageField(default='default_pic', null=True, upload_to='MyFarm/photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Guestbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('create_date', models.DateTimeField()),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostPics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Post_pics', models.ImageField(default='default_pic', null=True, upload_to='MyFarm/photos/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Farmer_pic', models.ImageField(default='default_pic', null=True, upload_to='Farmer_pic')),
                ('Farmer_name', models.CharField(max_length=50, null=True)),
                ('Farmer_tel', models.CharField(max_length=100, unique=True)),
                ('Farmer_intro', models.TextField(default='반갑습니다', null=True)),
                ('Farmer_others', models.ManyToManyField(to='farmin.user')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('create_date', models.DateTimeField()),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
                ('Post_pic', models.ManyToManyField(to='farmin.postpics')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmin.user')),
                ('like', models.ManyToManyField(blank=True, related_name='likes', to='farmin.user')),
            ],
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Farm_pic', models.ManyToManyField(to='farmin.farmpics')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmin.user')),
            ],
        ),
    ]
