# Generated by Django 4.2.4 on 2023-08-08 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Guestbook',
            new_name='Comment',
        ),
    ]
