# Generated by Django 4.2.4 on 2023-08-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmin', '0004_alter_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Post_pic',
            field=models.ManyToManyField(blank=True, to='farmin.postpics'),
        ),
    ]
