# Generated by Django 4.2.4 on 2023-08-11 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmin', '0008_alter_post_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
    ]
