# Generated by Django 4.2.4 on 2023-08-13 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmin', '0009_remove_post_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='like',
        ),
        migrations.AddField(
            model_name='post',
            name='like',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
