# Generated by Django 4.2.4 on 2023-08-14 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmin', '0012_remove_post_like_post_like'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Guestbook',
        ),
    ]
