# Generated by Django 4.2.3 on 2023-08-14 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmin', '0013_alter_post_title_likeduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
