# Generated by Django 4.2.3 on 2023-08-15 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmin', '0013_rename_comment_guestbook'),
        ('farmin', '0014_alter_post_title'),
    ]

    operations = [
    ]
