# Generated by Django 4.2.3 on 2023-08-15 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmin', '0015_merge_20230815_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Farmer_back_pic',
            field=models.ImageField(default='default_pic', null=True, upload_to='Farmer_back_pic'),
        ),
    ]
