# Generated by Django 4.2.3 on 2023-08-15 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmin', '0016_user_farmer_back_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='Farm_pic',
        ),
        migrations.AddField(
            model_name='farmpics',
            name='Farm_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='farmin.farm'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='farmpics',
            name='Farm_pics',
            field=models.ImageField(default='default_pic', null=True, upload_to='FarmPics'),
        ),
    ]
