# Generated by Django 4.2.4 on 2023-08-15 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmin', '0016_user_farmer_back_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestbook',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='farmin.user'),
            preserve_default=False,
        ),
    ]
