# Generated by Django 4.2.3 on 2023-08-16 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmin', '0017_remove_farm_farm_pic_farmpics_farm_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Farmer_back_pic',
            field=models.TextField(default='path_to_default_pic', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Farmer_pic',
            field=models.TextField(default='path_to_default_pic', null=True),
        ),
    ]
