# Generated by Django 4.2.4 on 2023-08-16 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmin', '0017_guestbook_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
