# Generated by Django 4.2.4 on 2023-08-16 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmin', '0018_remove_post_title_post_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestbook',
            name='modify_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='modify_date',
        ),
    ]
