# Generated by Django 4.2.3 on 2023-08-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmin', '0018_alter_user_farmer_back_pic_alter_user_farmer_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmpics',
            name='Farm_pics',
            field=models.TextField(default='path_to_default_pic', null=True),
        ),
    ]
