# Generated by Django 4.2.4 on 2023-08-16 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmin', '0019_remove_guestbook_modify_date_remove_post_modify_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmpics',
            name='Farm_pics',
            field=models.TextField(default='default_pic', null=True),
        ),
        migrations.AlterField(
            model_name='postpics',
            name='Post_pics',
            field=models.TextField(default='default_pic', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Farmer_back_pic',
            field=models.TextField(default='default_pic', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Farmer_pic',
            field=models.TextField(default='default_pic', null=True),
        ),
    ]
