# Generated by Django 4.2.3 on 2023-08-16 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmin', '0019_alter_farmpics_farm_pics'),
        ('farmin', '0022_post_price_alter_post_title'),
    ]

    operations = [
    ]
