# Generated by Django 4.2.3 on 2023-08-16 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmin', '0024_remove_post_post_pic_postpics_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Post_pics',
            field=models.TextField(default='default_pic', null=True),
        ),
        migrations.DeleteModel(
            name='PostPics',
        ),
    ]
