# Generated by Django 4.2.3 on 2023-08-17 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmin', '0025_post_post_pics_delete_postpics'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikedUser',
        ),
    ]
