# Generated by Django 4.2.3 on 2023-08-17 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmin', '0026_delete_likeduser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Neighbor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.TextField(default='path_to_default_pic', null=True)),
                ('name', models.CharField(max_length=50)),
                ('intro', models.CharField(max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='farmin.user')),
            ],
        ),
    ]
