# Generated by Django 4.2.4 on 2023-08-17 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmin', '0028_alter_post_author_alter_user_farmer_others_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_pic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='farmin.user'),
            preserve_default=False,
        ),
    ]
