# Generated by Django 4.2.4 on 2023-08-17 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmin', '0029_post_author_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Post_pics',
            field=models.TextField(blank=True, default='default_pic', null=True),
        ),
    ]
