# Generated by Django 4.2.4 on 2023-08-17 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmin', '0030_alter_post_post_pics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Post_pics',
            field=models.TextField(default='default_pic', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='author_pic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farmin.user'),
        ),
    ]
